[package]
name = "raytracing"
version = "0.0.0"
edition = "2021"
authors = ["Calbabreaker <calbabreaker@gmail.com>"]

[dependencies]
glam = "0.29"
fastrand = "2"
image = { version = "0.25", default-features = false, features = ["png"] }
