[package]
name = "raytracing"
version = "0.0.0"
edition = "2021"
authors = ["Calbabreaker <calbabreaker@gmail.com>"]

[dependencies]
glam = "0.20.1"
fastrand = "1.5.0"
num_cpus = "1.13.0"
image = { version = "0.24.1", default-features = false, features = ["png"] }

[profile.release]
debug = true
